compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmPublishAccess: public

npmScopes:
  pendle:
    npmAlwaysAuth: true
    npmAuthToken: "${PENDLE_AUTH_TOKEN:-Missing access token}"
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-4.12.0.cjs

npmMinimalAgeGate: 14d

npmPreapprovedPackages:
  - "@pendle/*"
