pragma solidity ^0.8.0;

library SDKErrorsDirectory {
    enum RateRejectReason {
        RATE_TOO_SMALL,
        RATE_TOO_LARGE
    }

    struct ExchangeRateData {
        uint128 rate;
        uint64 dataBlock; // the pin block which the data is sampled at
        uint32 dataTimestamp; // block(dataBlock).timestamp
        uint32 updatedAt;
    }

    error ApproxBinarySearchInputInvalid(
        uint256 approxGuessMin,
        uint256 approxGuessMax,
        uint256 minGuessMin,
        uint256 maxGuessMax
    );
    error ApproxDstExecutionGasNotSet();
    error ApproxFail();
    error ApproxParamsInvalid(uint256 guessMin, uint256 guessMax, uint256 eps);
    error ArrayEmpty();
    error ArrayLengthMismatch();
    error ArrayOutOfBounds();
    error BDInvalidEpoch(uint256 epoch, uint256 startTime);
    error BulkBadRateSyToToken(uint256 actualRate, uint256 currentRate, uint256 eps);
    error BulkBadRateTokenToSy(uint256 actualRate, uint256 currentRate, uint256 eps);
    error BulkInSufficientSyOut(uint256 actualSyOut, uint256 requiredSyOut);
    error BulkInSufficientTokenOut(uint256 actualTokenOut, uint256 requiredTokenOut);
    error BulkInsufficientSyForTrade(uint256 currentAmount, uint256 requiredAmount);
    error BulkInsufficientSyReceived(uint256 actualBalance, uint256 requiredBalance);
    error BulkInsufficientTokenForTrade(uint256 currentAmount, uint256 requiredAmount);
    error BulkNotAdmin();
    error BulkNotMaintainer();
    error BulkSellerAlreadyExisted(address token, address SY, address bulk);
    error BulkSellerInvalidToken(address token, address SY);
    error CallThenRevertError(bool success, bytes res);
    error ChainNotSupported(uint256 chainId);
    error CooldownNotComplete();
    error EmergencyEnabled();
    error Expired();
    error ExpiryInThePast(uint256 expiry);
    error FDEpochLengthMismatch();
    error FDFutureFunding(uint256 lastFunded, uint256 currentWTime);
    error FDInvalidNewFinishedEpoch(uint256 oldFinishedEpoch, uint256 newFinishedEpoch);
    error FDInvalidPool(address pool);
    error FDInvalidStartEpoch(uint256 startEpoch);
    error FDInvalidWTimeFund(uint256 lastFunded, uint256 wTime);
    error FDPoolAlreadyExists(address pool);
    error FDTotalAmountFundedNotMatch(uint256 actualTotalAmount, uint256 expectedTotalAmount);
    error FailToAdd();
    error FailToRemove();
    error FailedToSendEther();
    error FarmNotFound();
    error FluxLendingError(uint256 errCode);
    error Forbidden();
    error GCNotPendleMarket(address caller);
    error GCNotVotingController(address caller);
    error InsufficientBalance();
    error InsufficientFeeToSendMsg(uint256 currentFee, uint256 requiredFee);
    error InvalidBlockRate(uint256 blockCycleNumerator);
    error InvalidDepositAmount();
    error InvalidFarm();
    error InvalidInput();
    error InvalidMerkleProof();
    error InvalidNft(uint256 tokenId);
    error InvalidRange();
    error InvalidRetryData();
    error InvalidReward();
    error InvalidTime();
    error InvalidTokenId(uint256 tokenId, uint256 positionId);
    error InvalidWTime(uint256 wTime);
    error LiquidityNotMatch();
    error MFNotPendleMarket(address addr);
    error MarketExchangeRateBelowOne(int256 exchangeRate);
    error MarketExpired();
    error MarketFactoryExpiredPt();
    error MarketFactoryInitialAnchorTooLow(int256 initialAnchor, int256 minInitialAnchor);
    error MarketFactoryInvalidPt();
    error MarketFactoryLnFeeRateRootTooHigh(uint80 lnFeeRateRoot, uint256 maxLnFeeRateRoot);
    error MarketFactoryMarketExists();
    error MarketFactoryOverriddenFeeTooHigh(uint80 overriddenFee, uint256 marketLnFeeRateRoot);
    error MarketFactoryReserveFeePercentTooHigh(uint8 reserveFeePercent, uint8 maxReserveFeePercent);
    error MarketFactoryZeroTreasury();
    error MarketInsufficientPtForTrade(int256 currentAmount, int256 requiredAmount);
    error MarketInsufficientPtReceived(uint256 actualBalance, uint256 requiredBalance);
    error MarketInsufficientSyReceived(uint256 actualBalance, uint256 requiredBalance);
    error MarketProportionMustNotEqualOne();
    error MarketProportionTooHigh(int256 proportion, int256 maxProportion);
    error MarketRateScalarBelowZero(int256 rateScalar);
    error MarketScalarRootBelowZero(int256 scalarRoot);
    error MarketZeroAmountsInput();
    error MarketZeroAmountsOutput();
    error MarketZeroLnImpliedRate();
    error MarketZeroTotalPtOrTotalAsset(int256 totalPt, int256 totalAsset);
    error MinimumRedeemAmountNotReached(uint256 amountToRedeem, uint256 minimumRedeemAmount);
    error MinimumStakeAmountNotReached(uint256 amountToStake, uint256 minimumStakeAmount);
    error MsgNotFromReceiveEndpoint(address sender);
    error MsgNotFromSendEndpoint(uint16 srcChainId, bytes path);
    error NotFromTrustedRemote(uint16 srcChainId, bytes path);
    error NotOwner();
    error OnlyLayerZeroEndpoint();
    error OnlyWhitelisted();
    error OnlyYCFactory();
    error OnlyYT();
    error OracleNotReady(bool increaseCardinalityRequired, bool oldestObservationSatisfied);
    error OracleTargetTooOld(uint32 target, uint32 oldest);
    error OracleUninitialized();
    error OracleZeroCardinality();
    error PhaseSettled();
    error PoolIdDoesNotExit();
    error PositionNotEligible();
    error RangeNotFound();
    error RangeNotMatch();
    error RouterCallbackNotPendleMarket(address caller);
    error RouterExceededLimitPtIn(uint256 actualPtIn, uint256 limitPtIn);
    error RouterExceededLimitSyIn(uint256 actualSyIn, uint256 limitSyIn);
    error RouterExceededLimitYtIn(uint256 actualYtIn, uint256 limitYtIn);
    error RouterInsufficientLpOut(uint256 actualLpOut, uint256 requiredLpOut);
    error RouterInsufficientPYOut(uint256 actualPYOut, uint256 requiredPYOut);
    error RouterInsufficientPtOut(uint256 actualPtOut, uint256 requiredPtOut);
    error RouterInsufficientPtRepay(uint256 actualPtRepay, uint256 requiredPtRepay);
    error RouterInsufficientSyOut(uint256 actualSyOut, uint256 requiredSyOut);
    error RouterInsufficientSyRepay(uint256 actualSyRepay, uint256 requiredSyRepay);
    error RouterInsufficientTokenOut(uint256 actualTokenOut, uint256 requiredTokenOut);
    error RouterInsufficientYtOut(uint256 actualYtOut, uint256 requiredYtOut);
    error RouterInvalidAction(bytes4 selector);
    error RouterInvalidFacet(address facet);
    error RouterKyberSwapDataZero();
    error RouterNotAllSyUsed(uint256 netSyDesired, uint256 netSyUsed);
    error RouterTimeRangeZero();
    error SAInsufficientTokenIn(address tokenIn, uint256 amountExpected, uint256 amountActual);
    error SYApeDepositAmountTooSmall(uint256 amountDeposited);
    error SYBalancerInvalidPid();
    error SYBalancerReentrancy();
    error SYCurve3crvPoolNotFound();
    error SYCurveInvalidPid();
    error SYInsufficientSharesOut(uint256 actualSharesOut, uint256 requiredSharesOut);
    error SYInsufficientTokenOut(uint256 actualTokenOut, uint256 requiredTokenOut);
    error SYInvalidRewardToken(address token);
    error SYInvalidTokenIn(address token);
    error SYInvalidTokenOut(address token);
    error SYQiTokenBorrowRateTooHigh(uint256 borrowRate, uint256 borrowRateMax);
    error SYQiTokenMintFailed(uint256 errCode);
    error SYQiTokenRedeemFailed(uint256 errCode);
    error SYQiTokenRedeemRewardsFailed(uint256 rewardAccruedType0, uint256 rewardAccruedType1);
    error SYStargateRedeemCapExceeded(uint256 amountLpDesired, uint256 amountLpRedeemable);
    error SYZeroDeposit();
    error SYZeroRedeem();
    error SimulationResults(bool success, bytes res);
    error StaderMaxDepositExceed(uint256 amountToDeposit, uint256 maxDeposit);
    error StaderMinDepositUnreached(uint256 amountToDeposit, uint256 minDeposit);
    error StakeNotFound();
    error TransferFailed();
    error TwapDurationTooLarge(uint32 duration, uint32 cardinalityRequired);
    error UnstakeCapacityTooLow(uint256 amountBondToRedeem, uint256 unstakeCapacity);
    error UnsupportedOperation();
    error UnsupportedOperationInSafeMode();
    error UnsupportedSelector(uint256 aggregatorType, bytes4 selector);
    error VCEpochNotFinalized(uint256 wTime);
    error VCExceededMaxWeight(uint256 totalWeight, uint256 maxWeight);
    error VCInactivePool(address pool);
    error VCPoolAlreadyActive(address pool);
    error VCPoolAlreadyAddAndRemoved(address pool);
    error VCZeroVePendle(address user);
    error VEExceededMaxLockTime();
    error VEInsufficientLockTime();
    error VEInvalidNewExpiry(uint256 newExpiry);
    error VENotAllowedReduceExpiry();
    error VEPositionNotExpired();
    error VEReceiveOldSupply(uint256 msgTime);
    error VEZeroAmountLocked();
    error VEZeroPosition();
    error VEZeroSlope(uint128 bias, uint128 slope);
    error YCExpired();
    error YCFactoryInterestFeeRateTooHigh(uint256 interestFeeRate, uint256 maxInterestFeeRate);
    error YCFactoryInvalidExpiry();
    error YCFactoryRewardFeeRateTooHigh(uint256 newRewardFeeRate, uint256 maxRewardFeeRate);
    error YCFactoryYieldContractExisted();
    error YCFactoryZeroExpiryDivisor();
    error YCFactoryZeroTreasury();
    error YCNoFloatingSy();
    error YCNotExpired();
    error YCNothingToRedeem();
    error YCPostExpiryDataNotSet();
    error YieldContractInsufficientSy(uint256 actualSy, uint256 requiredSy);
    error ZeroAddress();
    error SupplyCapExceeded(uint256 totalSupply, uint256 supplyCap);
    error ShareTransferNotAllowed();
    error SenderNotSolventAfterTransfer();
    error ERC20InsufficientAllowance(address, uint256, uint256);
    error ERC20InsufficientBalance(address, uint256, uint256);
    error IXERC20_NotHighEnoughLimits();
    error ReturnAmountIsNotEnough();
    error ErrorNotEnoughAllowance();
    error OnlyManager();
    error OnlyTradingPnlHandler();
    error OnlyPnlFeed();
    error AddressZero();
    error PriceZero();
    error ValueZero();
    error BytesZero();
    error NoActiveDiscount();
    error BelowMin();
    error AboveMax();
    error WrongValue();
    error WrongValues();
    error GnsPriceCallFailed();
    error GnsTokenPriceZero();
    error PendingWithdrawal();
    error EndOfEpoch();
    error NotAllowed();
    error NoDiscount();
    error NotUnlocked();
    error NotEnoughAssets();
    error MaxDailyPnl();
    error NotUnderCollateralized();
    error AboveInflationLimit();
    error OwnableInvalidOwner(address owner);
    error ERC4626ExceededMaxDeposit();
    error ERC4626ExceededMaxMint();
    error ERC4626ExceededMaxWithdraw();
    error ERC4626ExceededMaxRedeem();

    error AccessControlUnauthorizedAccount(address account, bytes32 neededRole);
    error AccessControlBadConfirmation();
    error ERC20InvalidSender(address sender);
    error ERC20InvalidReceiver(address receiver);
    error ERC20InvalidApprover(address approver);
    error ERC20InvalidSpender(address spender);
    error ERC721InvalidOwner(address owner);
    error ERC721NonexistentToken(uint256 tokenId);
    error ERC721IncorrectOwner(address sender, uint256 tokenId, address owner);
    error ERC721InvalidSender(address sender);
    error ERC721InvalidReceiver(address receiver);
    error ERC721InsufficientApproval(address operator, uint256 tokenId);
    error ERC721InvalidApprover(address approver);
    error ERC721InvalidOperator(address operator);
    error ERC1155InsufficientBalance(address sender, uint256 balance, uint256 needed, uint256 tokenId);
    error ERC1155InvalidSender(address sender);
    error ERC1155InvalidReceiver(address receiver);
    error ERC1155MissingApprovalForAll(address operator, address owner);
    error ERC1155InvalidApprover(address approver);
    error ERC1155InvalidOperator(address operator);
    error ERC1155InvalidArrayLength(uint256 idsLength, uint256 valuesLength);
    error SafeERC20FailedOperation(address token);
    error SafeERC20FailedDecreaseAllowance(address spender, uint256 currentAllowance, uint256 requestedDecrease);
    error AddressInsufficientBalance(address account);
    error AddressEmptyCode(address target);
    error FailedInnerCall();
    error ReentrancyGuardReentrantCall();
    error MathOverflowedMulDiv();
    error Deadline();
    error InvalidState();
    error InvalidLength();
    error InvalidToken();
    error NonZeroValue();
    error InsufficientLpAmount();
    error InsufficientAmount();
    error LimitOverflow();
    error AlreadyAdded();
    error InvalidDelay();
    error InvalidTimestamp();
    error InvalidWithdrawalFee();
    error InvalidTotalSupply();
    error OperationNotAllowed();
    error WOMBAT_COV_RATIO_LIMIT_EXCEEDED();
    error NotEnoughLiquidity();
    error InvalidAmountToDeposit();
    error TellerWithMultiAssetSupport__AssetNotSupported();

    error SameIncentiveController();

    error KarakVaultAssetLimitExceeded(uint256 assetLimit, uint256 totalAsset, uint256 amountAssetToDeposit);
    error MellowVaultHasInvalidAssets();

    error ApxETHNotEnoughBuffer();
    error MaxStTAOSupplyExceeded(uint256 amountTaoToWrap, uint256 maxTaoForWrap);
    error VenusError(uint256 errorCode);
    error AMOUNT_NULL();
    error ADDRESS_NULL();
    error INSUFFICIENT_BALANCE();
    error TOKEN_NOT_ALLOWED(address token);
    error RateRejected(uint256 oldRate, uint256 newRate, RateRejectReason reason);
    error InvalidMetadata(ExchangeRateData data);
    error InvalidRoundId();
    error OracleAlreadyExists();
    error OracleIncreaseCardinalityRequired(uint32 cardinalityRequired);
    error OracleOldestObservationNotSatisfied();
    error IncreaseCardinalityRequired(uint16 cardinalityRequired);
    error AdditionalWaitRequired(uint32 duration);

    error LombardStakeLimitExceed(uint256 remainingStake, uint256 amountStaking);
    error AstherusYieldProxyActivitiesOnGoing();
    error NotEnoughNative(uint256 msgValue);
    error LzTokenUnavailable();
    error OnlyPeer(uint32 eid, bytes32 sender);
    error NoPeer(uint32 eid);
    error InvalidEndpointCall();
    error InvalidDelegate();
    error InvalidLocalDecimals();
    error SlippageExceeded(uint256 amountLD, uint256 minAmountLD);
    error InvalidInitialization();
    error NotInitializing();
    error UUPSUnauthorizedCallContext();
    error UUPSUnsupportedProxiableUUID(bytes32 slot);
    error EnforcedPause();
    error ExpectedPause();
    error OwnableUnauthorizedAccount(address account);
    error ERC1967InvalidImplementation(address implementation);
    error ERC1967InvalidAdmin(address admin);
    error ERC1967InvalidBeacon(address beacon);
    error ERC1967NonPayable();
    error ERC2612ExpiredSignature(uint256 deadline);
    error ERC2612InvalidSigner(address signer, address owner);
    error InvalidAccountNonce(address account, uint256 currentNonce);
    error StringTooLong(string str);
    error InvalidShortString();
    error StringsInsufficientHexLength(uint256 value, uint256 length);
    error ECDSAInvalidSignature();
    error ECDSAInvalidSignatureLength(uint256 length);
    error ECDSAInvalidSignatureS(bytes32 s);

    error MoonwellMintError(uint256 errorCode);
    error MoonwellRedeemError(uint256 errorCode);
    error PendingRewardNonZero(address rewardToken, uint256 amount);

    error INVALID_REBALANCE_SELECTOR();
    error BLOCK_CHAIN_ID_OUT_OF_BOUNDS();
    error CANNOT_REVOKE_NON_BROADCASTABLE_ROLES();
    error CANNOT_REVOKE_LAST_ADMIN();
    error DISABLED();
    error DELAY_NOT_SET();
    error INVALID_NATIVE_TOKEN_PRICE();
    error REFUND_CHAIN_ID_NOT_SET();
    error RELAYER_NOT_SET();
    error ROLE_NOT_ASSIGNED();
    error INVALID_INTERNAL_CALL();
    error NOT_AMB_IMPLEMENTATION();
    error NOT_ALLOWED_BROADCASTER();
    error NOT_BROADCAST_AMB_IMPLEMENTATION();
    error NOT_BROADCAST_REGISTRY();
    error NOT_CORE_STATE_REGISTRY();
    error NOT_EMERGENCY_ADMIN();
    error NOT_EMERGENCY_QUEUE();
    error NOT_MINTER();
    error NOT_MINTER_STATE_REGISTRY_ROLE();
    error NOT_PAYMASTER();
    error NOT_PAYMENT_ADMIN();
    error NOT_PROTOCOL_ADMIN();
    error NOT_STATE_REGISTRY();
    error NOT_SUPER_REGISTRY();
    error NOT_SUPERFORM_ROUTER();
    error NOT_SUPERFORM();
    error NOT_SUPERFORM_FACTORY();
    error NOT_TIMELOCK_SUPERFORM();
    error NOT_TIMELOCK_STATE_REGISTRY();
    error NOT_VALID_DISPUTER();
    error NOT_PRIVILEGED_CALLER(bytes32 role);
    error CALLER_NOT_ENDPOINT();
    error CALLER_NOT_MAILBOX();
    error CALLER_NOT_RELAYER();
    error INVALID_SRC_SENDER();
    error ARRAY_LENGTH_MISMATCH();
    error INVALID_PAYLOAD_ID();
    error MSG_VALUE_NOT_ZERO();
    error ZERO_AMB_ID_LENGTH();
    error ZERO_ADDRESS();
    error ZERO_AMOUNT();
    error ZERO_FINAL_TOKEN();
    error ZERO_INPUT_VALUE();
    error INVALID_SUPERFORMS_DATA();
    error RECEIVER_ADDRESS_NOT_SET();
    error ERC165_UNSUPPORTED();
    error FORM_INTERFACE_UNSUPPORTED();
    error FORM_IMPLEMENTATION_ALREADY_EXISTS();
    error FORM_IMPLEMENTATION_ID_ALREADY_EXISTS();
    error FORM_DOES_NOT_EXIST();
    error INVALID_FORM_ID();
    error SUPERFORM_ID_NONEXISTENT();
    error VAULT_FORM_IMPLEMENTATION_COMBINATION_EXISTS();
    error DIFFERENT_TOKENS();
    error DIRECT_WITHDRAW_INVALID_LIQ_REQUEST();
    error XCHAIN_WITHDRAW_INVALID_LIQ_REQUEST();
    error BLACKLISTED_ROUTE_ID();
    error NOT_BLACKLISTED_ROUTE_ID();
    error BLACKLISTED_SELECTOR();
    error NOT_BLACKLISTED_SELECTOR();
    error INVALID_ACTION();
    error INVALID_DEPOSIT_LIQ_DST_CHAIN_ID();
    error INVALID_INDEX();
    error INVALID_TXDATA_CHAIN_ID();
    error INVALID_TXDATA_NO_DESTINATIONCALL_ALLOWED();
    error INVALID_TXDATA_RECEIVER();
    error INVALID_TXDATA_TOKEN();
    error NO_TXDATA_PRESENT();
    error DIFFERENT_PAYLOAD_UPDATE_AMOUNTS_LENGTH();
    error DIFFERENT_PAYLOAD_UPDATE_TX_DATA_LENGTH();
    error INVALID_UPDATE_FINAL_TOKEN();
    error INVALID_BROADCAST_FINALITY();
    error INVALID_BRIDGE_ID();
    error INVALID_CHAIN_ID();
    error INVALID_DST_SWAP_AMOUNT();
    error INVALID_PROOF_BRIDGE_ID();
    error INVALID_PROOF_BRIDGE_IDS();
    error INVALID_RESCUE_DATA();
    error INVALID_TIMELOCK_DELAY();
    error NEGATIVE_SLIPPAGE();
    error SLIPPAGE_OUT_OF_BOUNDS();
    error SRC_SENDER_MISMATCH();
    error SRC_TX_TYPE_MISMATCH();
    error DIRECT_DEPOSIT_SWAP_FAILED();
    error DUPLICATE_PAYLOAD();
    error FAILED_TO_SEND_NATIVE();
    error INSUFFICIENT_ALLOWANCE_FOR_DEPOSIT();
    error INSUFFICIENT_NATIVE_AMOUNT();
    error INVALID_PAYLOAD();
    error INVALID_PAYLOAD_STATUS();
    error INVALID_PAYLOAD_TYPE();
    error CANNOT_DECODE_FINAL_SWAP_OUTPUT_TOKEN();
    error FAILED_TO_EXECUTE_TXDATA(address token);
    error INVALID_DEPOSIT_TOKEN();
    error BRIDGE_TOKENS_PENDING();
    error CANNOT_UPDATE_WITHDRAW_TX_DATA();
    error DISPUTE_TIME_ELAPSED();
    error INSUFFICIENT_QUORUM();
    error INVALID_BROADCAST_PAYLOAD();
    error INVALID_BROADCAST_FEE();
    error INVALID_RETRY_FEE();
    error INVALID_MESSAGE_TYPE();
    error INVALID_PAYLOAD_HASH();
    error INVALID_PAYLOAD_UPDATE_REQUEST();
    error INVALID_REGISTRY_ID();
    error INVALID_FORM_REGISTRY_ID();
    error LOCKED();
    error PAYLOAD_ALREADY_UPDATED();
    error PAYLOAD_ALREADY_PROCESSED();
    error PAYLOAD_NOT_UPDATED();
    error RESCUE_LOCKED();
    error RESCUE_ALREADY_PROPOSED();
    error ZERO_PAYLOAD_HASH();
    error DST_SWAP_ALREADY_PROCESSED();
    error DUPLICATE_INDEX();
    error FAILED_DST_SWAP_ALREADY_UPDATED();
    error INDEX_OUT_OF_BOUNDS();
    error INVALID_DST_SWAPPER_FAILED_SWAP();
    error INVALID_DST_SWAPPER_FAILED_SWAP_NO_TOKEN_BALANCE();
    error INVALID_DST_SWAPPER_FAILED_SWAP_NO_NATIVE_BALANCE();
    error INVALID_INTERIM_TOKEN();
    error INVALID_SWAP_OUTPUT();
    error CANNOT_FORWARD_4646_TOKEN();
    error NO_VALID_KYC_TOKEN();
    error NOT_IMPLEMENTED();
    error PAUSED();
    error VAULT_IMPLEMENTATION_FAILED();
    error WITHDRAW_TOKEN_NOT_UPDATED();
    error WITHDRAW_TX_DATA_NOT_UPDATED();
    error WITHDRAW_ZERO_COLLATERAL();
    error CHAINLINK_MALFUNCTION();
    error CHAINLINK_INCOMPLETE_ROUND();
    error CHAINLINK_UNSUPPORTED_DECIMAL();
    error EMERGENCY_WITHDRAW_NOT_QUEUED();
    error EMERGENCY_WITHDRAW_PROCESSED_ALREADY();
    error DYNAMIC_URI_FROZEN();
    error TX_HISTORY_NOT_FOUND();
    error AERC20_ALREADY_REGISTERED();
    error AERC20_NOT_REGISTERED();
    error DECREASED_ALLOWANCE_BELOW_ZERO();
    error ID_NOT_MINTED_YET();
    error LENGTH_MISMATCH();
    error TRANSFER_TO_ADDRESS_ZERO();
    error ZERO_SUPERFORMS();
    error ZERO_ID();
    error DUPLICATE_SUPERFORM_IDS_REBALANCE_FROM();
    error DUPLICATE_FINAL_SUPERFORM_IDS();
    error INVALID_WEIGHTS();
    error NOT_SUPER_VAULTS_STRATEGIST();
    error EMPTY_AMOUNTS_REBALANCE_FROM();
    error EMPTY_FINAL_SUPERFORM_IDS();
    error SUPERFORM_DOES_NOT_SUPPORT_ASSET();
    error SUPERFORM_DOES_NOT_EXIST(uint256 superformId);
    error INVALID_SUPERFORM_ID_REBALANCE_FROM();
    error REBALANCE_FROM_ID_NOT_FOUND_IN_FINAL_IDS();
    error NOT_PENDING_MANAGEMENT();
    error NOT_VAULT_MANAGER();
    error SUPERFORM_NOT_WHITELISTED();
    error INVALID_SP_FULL_REBALANCE(uint256 superformId);
    error INVALID_REBALANCE_FROM_SELECTOR();
    error INVALID_DEPOSIT_SELECTOR();
    error REBALANCE_SINGLE_POSITIONS_DIFFERENT_TOKEN();
    error REBALANCE_SINGLE_POSITIONS_DIFFERENT_CHAIN();
    error REBALANCE_SINGLE_POSITIONS_DIFFERENT_AMOUNT();
    error REBALANCE_SINGLE_POSITIONS_UNEXPECTED_RECEIVER_ADDRESS();
    error REBALANCE_MULTI_POSITIONS_DIFFERENT_TOKEN();
    error REBALANCE_MULTI_POSITIONS_DIFFERENT_CHAIN();
    error REBALANCE_MULTI_POSITIONS_DIFFERENT_AMOUNTS();
    error REBALANCE_MULTI_POSITIONS_UNEXPECTED_RECEIVER_ADDRESS();
    error REBALANCE_XCHAIN_INVALID_RECEIVER_ADDRESS();
    error INVALID_FEE();
    error ASSETS_RECEIVED_OUT_OF_SLIPPAGE();
    error INVALID_GLOBAL_SLIPPAGE();
    error TOLERANCE_EXCEEDED();
    error AMOUNT_IN_NOT_EQUAL_OR_LOWER_THAN_BALANCE();
}
