pragma solidity ^0.8.0;

library SDKErrorsDirectory {
    error ApproxBinarySearchInputInvalid(
        uint256 approxGuessMin,
        uint256 approxGuessMax,
        uint256 minGuessMin,
        uint256 maxGuessMax
    );
    error ApproxDstExecutionGasNotSet();
    error ApproxFail();
    error ApproxParamsInvalid(uint256 guessMin, uint256 guessMax, uint256 eps);
    error ArrayEmpty();
    error ArrayLengthMismatch();
    error ArrayOutOfBounds();
    error BDInvalidEpoch(uint256 epoch, uint256 startTime);
    error BulkBadRateSyToToken(uint256 actualRate, uint256 currentRate, uint256 eps);
    error BulkBadRateTokenToSy(uint256 actualRate, uint256 currentRate, uint256 eps);
    error BulkInSufficientSyOut(uint256 actualSyOut, uint256 requiredSyOut);
    error BulkInSufficientTokenOut(uint256 actualTokenOut, uint256 requiredTokenOut);
    error BulkInsufficientSyForTrade(uint256 currentAmount, uint256 requiredAmount);
    error BulkInsufficientSyReceived(uint256 actualBalance, uint256 requiredBalance);
    error BulkInsufficientTokenForTrade(uint256 currentAmount, uint256 requiredAmount);
    error BulkNotAdmin();
    error BulkNotMaintainer();
    error BulkSellerAlreadyExisted(address token, address SY, address bulk);
    error BulkSellerInvalidToken(address token, address SY);
    error CallThenRevertError(bool success, bytes res);
    error ChainNotSupported(uint256 chainId);
    error CooldownNotComplete();
    error EmergencyEnabled();
    error Expired();
    error ExpiryInThePast(uint256 expiry);
    error FDEpochLengthMismatch();
    error FDFutureFunding(uint256 lastFunded, uint256 currentWTime);
    error FDInvalidNewFinishedEpoch(uint256 oldFinishedEpoch, uint256 newFinishedEpoch);
    error FDInvalidPool(address pool);
    error FDInvalidStartEpoch(uint256 startEpoch);
    error FDInvalidWTimeFund(uint256 lastFunded, uint256 wTime);
    error FDPoolAlreadyExists(address pool);
    error FDTotalAmountFundedNotMatch(uint256 actualTotalAmount, uint256 expectedTotalAmount);
    error FailToAdd();
    error FailToRemove();
    error FailedToSendEther();
    error FarmNotFound();
    error FluxLendingError(uint256 errCode);
    error Forbidden();
    error GCNotPendleMarket(address caller);
    error GCNotVotingController(address caller);
    error InsufficientBalance();
    error InsufficientFeeToSendMsg(uint256 currentFee, uint256 requiredFee);
    error InvalidBlockRate(uint256 blockCycleNumerator);
    error InvalidDepositAmount();
    error InvalidFarm();
    error InvalidInput();
    error InvalidMerkleProof();
    error InvalidNft(uint256 tokenId);
    error InvalidRange();
    error InvalidRetryData();
    error InvalidReward();
    error InvalidTime();
    error InvalidTokenId(uint256 tokenId, uint256 positionId);
    error InvalidWTime(uint256 wTime);
    error LiquidityNotMatch();
    error MFNotPendleMarket(address addr);
    error MarketExchangeRateBelowOne(int256 exchangeRate);
    error MarketExpired();
    error MarketFactoryExpiredPt();
    error MarketFactoryInitialAnchorTooLow(int256 initialAnchor, int256 minInitialAnchor);
    error MarketFactoryInvalidPt();
    error MarketFactoryLnFeeRateRootTooHigh(uint80 lnFeeRateRoot, uint256 maxLnFeeRateRoot);
    error MarketFactoryMarketExists();
    error MarketFactoryOverriddenFeeTooHigh(uint80 overriddenFee, uint256 marketLnFeeRateRoot);
    error MarketFactoryReserveFeePercentTooHigh(uint8 reserveFeePercent, uint8 maxReserveFeePercent);
    error MarketFactoryZeroTreasury();
    error MarketInsufficientPtForTrade(int256 currentAmount, int256 requiredAmount);
    error MarketInsufficientPtReceived(uint256 actualBalance, uint256 requiredBalance);
    error MarketInsufficientSyReceived(uint256 actualBalance, uint256 requiredBalance);
    error MarketProportionMustNotEqualOne();
    error MarketProportionTooHigh(int256 proportion, int256 maxProportion);
    error MarketRateScalarBelowZero(int256 rateScalar);
    error MarketScalarRootBelowZero(int256 scalarRoot);
    error MarketZeroAmountsInput();
    error MarketZeroAmountsOutput();
    error MarketZeroLnImpliedRate();
    error MarketZeroTotalPtOrTotalAsset(int256 totalPt, int256 totalAsset);
    error MinimumRedeemAmountNotReached(uint256 amountToRedeem, uint256 minimumRedeemAmount);
    error MinimumStakeAmountNotReached(uint256 amountToStake, uint256 minimumStakeAmount);
    error MsgNotFromReceiveEndpoint(address sender);
    error MsgNotFromSendEndpoint(uint16 srcChainId, bytes path);
    error NotFromTrustedRemote(uint16 srcChainId, bytes path);
    error NotOwner();
    error OnlyLayerZeroEndpoint();
    error OnlyWhitelisted();
    error OnlyYCFactory();
    error OnlyYT();
    error OracleNotReady(bool increaseCardinalityRequired, bool oldestObservationSatisfied);
    error OracleTargetTooOld(uint32 target, uint32 oldest);
    error OracleUninitialized();
    error OracleZeroCardinality();
    error PhaseSettled();
    error PoolIdDoesNotExit();
    error PositionNotEligible();
    error RangeNotFound();
    error RangeNotMatch();
    error RouterCallbackNotPendleMarket(address caller);
    error RouterExceededLimitPtIn(uint256 actualPtIn, uint256 limitPtIn);
    error RouterExceededLimitSyIn(uint256 actualSyIn, uint256 limitSyIn);
    error RouterExceededLimitYtIn(uint256 actualYtIn, uint256 limitYtIn);
    error RouterInsufficientLpOut(uint256 actualLpOut, uint256 requiredLpOut);
    error RouterInsufficientPYOut(uint256 actualPYOut, uint256 requiredPYOut);
    error RouterInsufficientPtOut(uint256 actualPtOut, uint256 requiredPtOut);
    error RouterInsufficientPtRepay(uint256 actualPtRepay, uint256 requiredPtRepay);
    error RouterInsufficientSyOut(uint256 actualSyOut, uint256 requiredSyOut);
    error RouterInsufficientSyRepay(uint256 actualSyRepay, uint256 requiredSyRepay);
    error RouterInsufficientTokenOut(uint256 actualTokenOut, uint256 requiredTokenOut);
    error RouterInsufficientYtOut(uint256 actualYtOut, uint256 requiredYtOut);
    error RouterInvalidAction(bytes4 selector);
    error RouterInvalidFacet(address facet);
    error RouterKyberSwapDataZero();
    error RouterNotAllSyUsed(uint256 netSyDesired, uint256 netSyUsed);
    error RouterTimeRangeZero();
    error SAInsufficientTokenIn(address tokenIn, uint256 amountExpected, uint256 amountActual);
    error SYApeDepositAmountTooSmall(uint256 amountDeposited);
    error SYBalancerInvalidPid();
    error SYBalancerReentrancy();
    error SYCurve3crvPoolNotFound();
    error SYCurveInvalidPid();
    error SYInsufficientSharesOut(uint256 actualSharesOut, uint256 requiredSharesOut);
    error SYInsufficientTokenOut(uint256 actualTokenOut, uint256 requiredTokenOut);
    error SYInvalidRewardToken(address token);
    error SYInvalidTokenIn(address token);
    error SYInvalidTokenOut(address token);
    error SYQiTokenBorrowRateTooHigh(uint256 borrowRate, uint256 borrowRateMax);
    error SYQiTokenMintFailed(uint256 errCode);
    error SYQiTokenRedeemFailed(uint256 errCode);
    error SYQiTokenRedeemRewardsFailed(uint256 rewardAccruedType0, uint256 rewardAccruedType1);
    error SYStargateRedeemCapExceeded(uint256 amountLpDesired, uint256 amountLpRedeemable);
    error SYZeroDeposit();
    error SYZeroRedeem();
    error SimulationResults(bool success, bytes res);
    error StaderMaxDepositExceed(uint256 amountToDeposit, uint256 maxDeposit);
    error StaderMinDepositUnreached(uint256 amountToDeposit, uint256 minDeposit);
    error StakeNotFound();
    error TransferFailed();
    error TwapDurationTooLarge(uint32 duration, uint32 cardinalityRequired);
    error UnstakeCapacityTooLow(uint256 amountBondToRedeem, uint256 unstakeCapacity);
    error UnsupportedOperation();
    error UnsupportedOperationInSafeMode();
    error UnsupportedSelector(uint256 aggregatorType, bytes4 selector);
    error VCEpochNotFinalized(uint256 wTime);
    error VCExceededMaxWeight(uint256 totalWeight, uint256 maxWeight);
    error VCInactivePool(address pool);
    error VCPoolAlreadyActive(address pool);
    error VCPoolAlreadyAddAndRemoved(address pool);
    error VCZeroVePendle(address user);
    error VEExceededMaxLockTime();
    error VEInsufficientLockTime();
    error VEInvalidNewExpiry(uint256 newExpiry);
    error VENotAllowedReduceExpiry();
    error VEPositionNotExpired();
    error VEReceiveOldSupply(uint256 msgTime);
    error VEZeroAmountLocked();
    error VEZeroPosition();
    error VEZeroSlope(uint128 bias, uint128 slope);
    error YCExpired();
    error YCFactoryInterestFeeRateTooHigh(uint256 interestFeeRate, uint256 maxInterestFeeRate);
    error YCFactoryInvalidExpiry();
    error YCFactoryRewardFeeRateTooHigh(uint256 newRewardFeeRate, uint256 maxRewardFeeRate);
    error YCFactoryYieldContractExisted();
    error YCFactoryZeroExpiryDivisor();
    error YCFactoryZeroTreasury();
    error YCNoFloatingSy();
    error YCNotExpired();
    error YCNothingToRedeem();
    error YCPostExpiryDataNotSet();
    error YieldContractInsufficientSy(uint256 actualSy, uint256 requiredSy);
    error ZeroAddress();
    error SupplyCapExceeded(uint256 totalSupply, uint256 supplyCap);
    error ShareTransferNotAllowed();
    error SenderNotSolventAfterTransfer();
    error ERC20InsufficientAllowance(address, uint256, uint256);
    error ERC20InsufficientBalance(address, uint256, uint256);
    error IXERC20_NotHighEnoughLimits();
    error ReturnAmountIsNotEnough();
    error ErrorNotEnoughAllowance();
    error OnlyManager();
    error OnlyTradingPnlHandler();
    error OnlyPnlFeed();
    error AddressZero();
    error PriceZero();
    error ValueZero();
    error BytesZero();
    error NoActiveDiscount();
    error BelowMin();
    error AboveMax();
    error WrongValue();
    error WrongValues();
    error GnsPriceCallFailed();
    error GnsTokenPriceZero();
    error PendingWithdrawal();
    error EndOfEpoch();
    error NotAllowed();
    error NoDiscount();
    error NotUnlocked();
    error NotEnoughAssets();
    error MaxDailyPnl();
    error NotUnderCollateralized();
    error AboveInflationLimit();
    error OwnableInvalidOwner(address owner);
    error ERC4626ExceededMaxDeposit();
    error ERC4626ExceededMaxMint();
    error ERC4626ExceededMaxWithdraw();
    error ERC4626ExceededMaxRedeem();

    error AccessControlUnauthorizedAccount(address account, bytes32 neededRole);
    error AccessControlBadConfirmation();
    error ERC20InvalidSender(address sender);
    error ERC20InvalidReceiver(address receiver);
    error ERC20InvalidApprover(address approver);
    error ERC20InvalidSpender(address spender);
    error ERC721InvalidOwner(address owner);
    error ERC721NonexistentToken(uint256 tokenId);
    error ERC721IncorrectOwner(address sender, uint256 tokenId, address owner);
    error ERC721InvalidSender(address sender);
    error ERC721InvalidReceiver(address receiver);
    error ERC721InsufficientApproval(address operator, uint256 tokenId);
    error ERC721InvalidApprover(address approver);
    error ERC721InvalidOperator(address operator);
    error ERC1155InsufficientBalance(address sender, uint256 balance, uint256 needed, uint256 tokenId);
    error ERC1155InvalidSender(address sender);
    error ERC1155InvalidReceiver(address receiver);
    error ERC1155MissingApprovalForAll(address operator, address owner);
    error ERC1155InvalidApprover(address approver);
    error ERC1155InvalidOperator(address operator);
    error ERC1155InvalidArrayLength(uint256 idsLength, uint256 valuesLength);
    error SafeERC20FailedOperation(address token);
    error SafeERC20FailedDecreaseAllowance(address spender, uint256 currentAllowance, uint256 requestedDecrease);
    error AddressInsufficientBalance(address account);
    error AddressEmptyCode(address target);
    error FailedInnerCall();
    error ReentrancyGuardReentrantCall();
    error MathOverflowedMulDiv();
    error Deadline();
    error InvalidState();
    error InvalidLength();
    error InvalidToken();
    error NonZeroValue();
    error InsufficientLpAmount();
    error InsufficientAmount();
    error LimitOverflow();
    error AlreadyAdded();
    error InvalidDelay();
    error InvalidTimestamp();
    error InvalidWithdrawalFee();
    error InvalidTotalSupply();
}
